export default 
[
    {
        id: 0,
        genre: 'Fantasy',
        rating: 5,
        title: 'Harry Potter and the Sorcerer\'s Stone',
        author: 'J.K. Rowling',
        summary: 'Story of a young boy who discovers on his 11th birthday, he is a wizard and is going to be attending a wizarding school called Hogwarts School of Witchcraft and Wizardry. This boy is Harry Potter.',
        image: require('../components/images/hp1.jpg'),
        link: 'https://www.amazon.com/Harry-Potter-Sorcerers-Stone-Rowling-ebook/dp/B0192CTMYG/ref=sr_1_4?dchild=1&keywords=harry+potter&qid=1625928417&s=books&sr=1-4'
    },
    {
        id: 1,
        genre: 'Fantasy',
        rating: 4,
        title: 'Harry Potter and the Chamber of Secrets',
        author: 'J.K. Rowling',
        summary: 'Second story in the series, Harry Potter attends his second year at Hogwarts. Something has been released in Hogwarts and is causing a danger to students, and it\'s up to Harry and friends to discover where it came from and solve its mysteries.',
        image: require('../components/images/hp2.jpg'),
        link: '',
    },
    {
        id: 2,
        genre: 'Fantasy',
        rating: 5,
        title: 'Harry Potter and the Prisoner of Azkaban',
        author: 'J.K. Rowling',
        summary: 'Third story in the series. Harry, attending his third year, discovers Hogwarts has new guards at the school, but learning they are not exactly friendly. Known accomplice of He Who Must Not Be Named, Sirius Black has escaped Azkaban!',
        image: require('../components/images/hp3.jpg'),
        link: '',
    },
    {
        id: 3,
        genre: 'Personal Finance',
        rating: 5,
        title: 'Rich Dad Poor Dad',
        author: 'Robert Kiyosaki',
        summary: 'How to use money as a tool for wealth development. It destroys the myth that the rich are born rich, explains why your personal residence may not really be an asset, describes the real difference between an asset and a liability, and much more...',
        image: require('../components/images/rdpd.jpg'),
        link: '',
    },
    {
        id: 4,
        genre: 'Personal Finance',
        rating: 5,
        title: 'Cashflow Quadrant',
        author: 'Robert Kiyosaki',
        summary: 'At its simplest, the Cashflow Quadrant is a way to categorize people based on where their money comes from: E, S, B, or I. E stands for an Employee, someone who earns money by holding a job. S is Self-employed, earning money for themselves...',
        image: require('../components/images/cfqb.jpg'),
        link: '',
    },
    {
        id: 5,
        genre: 'Non-Fiction',
        rating: 5,
        title: 'The 4-Hour Work Week',
        author: 'Timothy Ferris',
        summary: '"The 4-Hour Work Week” is a powerful book on lifestyle design for anyone that wants to put living before working. Tim\'s goal is to show the reader not only how to design their ideal lifestyle but also exactly how to get there...',
        image: require('../components/images/4hww.jpg'),
        link: '',
    },
    {
        id: 6,
        genre: 'Non-Fiction',
        rating: 4.5,
        title: 'The Art of War',
        author: 'Sun Tzu',
        summary: 'Probably the most important point of "The Art of War" tries to make is that information does matter, and an educated guess is better than a gut decision. Sun Tzu thought that generals should be adept at the "military calculus" of taking into account anything and everything that could affect the outcome of a battle.',
        image: require('../components/images/aow.jpg'),
        link: '',
    },
    {
        id: 7,
        genre: 'Non-Fiction',
        rating: 5,
        title: 'Contagious: Why Things Catch On',
        author: 'Jonah Berger',
        summary: 'Why do some products and ideas spread like wildfire while others fail to catch on? In this book, Wharton marketing professor Jonah Berger shares the 6 STEPPS or ingredients for creating viral content that are more likely to spread via word-of-mouth.',
        image: require('../components/images/conta.jpg'),
        link: '',
    },
    {
        id: 8,
        genre: 'Non-Fiction',
        rating: 5,
        title: 'Richest Man in Babylon',
        author: 'George S. Clason',
        summary: '"The 4-Hour Work Week” is a powerful book on lifestyle design for anyone that wants to put living before working. Tim\'s goal is to show the reader not only how to design their ideal lifestyle but also exactly how to get there...',
        image: require('../components/images/rmib.jpg'),
        link: 'https://www.amazon.com/Richest-Man-Babylon-George-Clason/dp/1942121288/ref=sr_1_5?crid=1PNUIPN5K0IIG&dchild=1&keywords=richest+man+in+babylon+book&qid=1625927324&sprefix=richest+man+in+%2Caps%2C251&sr=8-5',
    },
]